const { JSDOM } = require("jsdom");
const fs = require("fs");
const html = fs.readFileSync("docs/index.html", "utf8");
const dom = new JSDOM(html, { runScripts: "dangerously", resources: "usable" });
dom.window.onerror = (m) => { console.error("JS ERROR:", m); process.exit(1); };
setTimeout(() => {
  const d = dom.window.document;
  const toggle = d.getElementById("menuToggle");
  const painel = d.getElementById("menuLateral");
  console.log("toggle existe:", !!toggle);
  console.log("painel classe antes:", painel.className);
  toggle.click();
  console.log("painel classe depois do clique:", painel.className);
  console.log("aria-hidden:", painel.getAttribute("aria-hidden"));
  console.log("itens do menu:", d.querySelectorAll(".menu-item").length);
  d.querySelectorAll(".menu-item span:first-of-type, .menu-item > span").forEach(s => console.log(" -", s.textContent));
  document.getElementById && null;
  const fechar = d.getElementById("menuFechar");
  fechar.click();
  console.log("painel classe depois de fechar:", painel.className);
  console.log("SEM ERRO");
}, 250);
